--
-- PostgreSQL database dump
--

-- Dumped from database version 15.4 (Debian 15.4-1.pgdg110+1)
-- Dumped by pg_dump version 15.4 (Debian 15.4-1.pgdg110+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: bookings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bookings (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    station_id bigint NOT NULL,
    charger_id bigint NOT NULL,
    port_number integer NOT NULL,
    start_time timestamp(6) without time zone NOT NULL,
    end_time timestamp(6) without time zone NOT NULL,
    status character varying(255) NOT NULL,
    fee numeric(12,2),
    total_price numeric(12,2),
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    CONSTRAINT bookings_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'CONFIRMED'::character varying, 'IN_PROGRESS'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying, 'EXPIRED'::character varying])::text[])))
);


--
-- Name: bookings_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.bookings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bookings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: chargers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chargers (
    id bigint NOT NULL,
    charge_point_model character varying(255),
    charge_point_serial character varying(255),
    charge_point_vendor character varying(255),
    connector_type character varying(255) NOT NULL,
    created_at timestamp(6) without time zone,
    firmware_version character varying(255),
    last_heartbeat timestamp(6) with time zone,
    max_power double precision NOT NULL,
    name character varying(255) NOT NULL,
    station_id bigint NOT NULL,
    status character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    CONSTRAINT chargers_connector_type_check CHECK (((connector_type)::text = ANY ((ARRAY['SOCKET_220V'::character varying, 'VINFAST_STD'::character varying, 'DATBIKE_FAST'::character varying, 'IEC_TYPE_2'::character varying, 'OTHER'::character varying])::text[]))),
    CONSTRAINT chargers_status_check CHECK (((status)::text = ANY ((ARRAY['AVAILABLE'::character varying, 'PREPARING'::character varying, 'CHARGING'::character varying, 'SUSPENDED_EVSE'::character varying, 'SUSPENDED_EV'::character varying, 'FINISHING'::character varying, 'RESERVED'::character varying, 'UNAVAILABLE'::character varying, 'FAULTED'::character varying, 'OFFLINE'::character varying])::text[])))
);


--
-- Name: chargers_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.chargers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chargers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: charging_sessions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.charging_sessions (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    end_time timestamp(6) without time zone,
    total_kwh numeric(10,4),
    booking_id bigint,
    invoice_id bigint,
    transaction_id integer,
    meter_start integer,
    port_id bigint NOT NULL,
    start_time timestamp(6) without time zone,
    status character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    user_id bigint NOT NULL,
    CONSTRAINT charging_sessions_status_check CHECK (((status)::text = ANY ((ARRAY['PREPARING'::character varying, 'CHARGING'::character varying, 'SUSPENDED_EV'::character varying, 'SUSPENDED_EVSE'::character varying, 'FINISHING'::character varying, 'COMPLETED'::character varying, 'FAULTED'::character varying, 'INTERRUPTED'::character varying])::text[])))
);


--
-- Name: charging_sessions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.charging_sessions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.charging_sessions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: complaint_responses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.complaint_responses (
    id bigint NOT NULL,
    complaint_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    message character varying(2000) NOT NULL,
    response_by bigint NOT NULL
);


--
-- Name: complaint_responses_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.complaint_responses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.complaint_responses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: complaints; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.complaints (
    id bigint NOT NULL,
    admin_note character varying(1000),
    created_at timestamp(6) without time zone,
    description character varying(2000) NOT NULL,
    resolved_at timestamp(6) without time zone,
    station_id bigint NOT NULL,
    status character varying(255) NOT NULL,
    title character varying(200) NOT NULL,
    updated_at timestamp(6) without time zone,
    user_id bigint NOT NULL,
    CONSTRAINT complaints_status_check CHECK (((status)::text = ANY ((ARRAY['OPEN'::character varying, 'IN_PROGRESS'::character varying, 'RESOLVED'::character varying, 'CLOSED'::character varying])::text[])))
);


--
-- Name: complaints_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.complaints ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.complaints_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: event_publication; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.event_publication (
    id uuid NOT NULL,
    completion_attempts integer NOT NULL,
    completion_date timestamp(6) with time zone,
    event_type character varying(255),
    last_resubmission_date timestamp(6) with time zone,
    listener_id character varying(255),
    publication_date timestamp(6) with time zone,
    serialized_event character varying(255),
    status character varying(255),
    CONSTRAINT event_publication_status_check CHECK (((status)::text = ANY ((ARRAY['PUBLISHED'::character varying, 'PROCESSING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying, 'RESUBMITTED'::character varying])::text[])))
);


--
-- Name: invoices; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.invoices (
    id bigint NOT NULL,
    booking_id bigint,
    charging_session_id bigint,
    created_at timestamp(6) without time zone,
    number character varying(255) NOT NULL,
    payment_method character varying(255),
    purpose character varying(255),
    status character varying(255) NOT NULL,
    total_cost numeric(12,2) NOT NULL,
    updated_at timestamp(6) without time zone,
    user_id bigint NOT NULL,
    CONSTRAINT invoices_payment_method_check CHECK (((payment_method)::text = ANY ((ARRAY['MOMO'::character varying, 'ZALOPAY'::character varying, 'BANK_TRANSFER'::character varying])::text[]))),
    CONSTRAINT invoices_purpose_check CHECK (((purpose)::text = ANY ((ARRAY['CHARGING_SESSION'::character varying, 'BOOKING'::character varying])::text[]))),
    CONSTRAINT invoices_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'PAID'::character varying, 'CANCELLED'::character varying, 'REFUNDED'::character varying])::text[])))
);


--
-- Name: invoices_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.invoices ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.invoices_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notifications (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    is_read boolean NOT NULL,
    message character varying(1000) NOT NULL,
    title character varying(200) NOT NULL,
    type character varying(255) NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT notifications_type_check CHECK (((type)::text = ANY ((ARRAY['BOOKING'::character varying, 'PAYMENT'::character varying, 'CHARGING'::character varying, 'SYSTEM'::character varying, 'PROMOTION'::character varying])::text[])))
);


--
-- Name: notifications_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ports; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ports (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    port_number integer NOT NULL,
    status character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    charger_id bigint NOT NULL,
    CONSTRAINT ports_status_check CHECK (((status)::text = ANY ((ARRAY['AVAILABLE'::character varying, 'PREPARING'::character varying, 'CHARGING'::character varying, 'SUSPENDED_EVSE'::character varying, 'SUSPENDED_EV'::character varying, 'FINISHING'::character varying, 'RESERVED'::character varying, 'UNAVAILABLE'::character varying, 'FAULTED'::character varying])::text[])))
);


--
-- Name: ports_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ports ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ports_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: price_settings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.price_settings (
    id bigint NOT NULL,
    booking_fee numeric(12,2),
    charging_rate_per_kwh numeric(12,2) NOT NULL,
    created_at timestamp(6) without time zone,
    effective_from timestamp(6) without time zone,
    grace_period_minutes integer NOT NULL,
    idle_penalty_per_minute numeric(12,2),
    is_active boolean NOT NULL,
    notes character varying(500),
    station_id bigint NOT NULL,
    version integer NOT NULL
);


--
-- Name: price_settings_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.price_settings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.price_settings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reviews; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reviews (
    id bigint NOT NULL,
    comment character varying(1000),
    created_at timestamp(6) without time zone,
    rating integer NOT NULL,
    station_id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    user_id bigint NOT NULL
);


--
-- Name: reviews_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.reviews ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reviews_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.roles (
    id bigint NOT NULL,
    name character varying(50) NOT NULL
);


--
-- Name: roles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: station_images; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.station_images (
    station_id bigint NOT NULL,
    image_url character varying(500)
);


--
-- Name: station_opening_hours; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.station_opening_hours (
    id bigint NOT NULL,
    close_time time(0) without time zone,
    day_of_week character varying(255) NOT NULL,
    is_open boolean,
    open_time time(0) without time zone,
    station_id bigint NOT NULL,
    CONSTRAINT station_opening_hours_day_of_week_check CHECK (((day_of_week)::text = ANY ((ARRAY['MONDAY'::character varying, 'TUESDAY'::character varying, 'WEDNESDAY'::character varying, 'THURSDAY'::character varying, 'FRIDAY'::character varying, 'SATURDAY'::character varying, 'SUNDAY'::character varying])::text[])))
);


--
-- Name: station_opening_hours_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.station_opening_hours ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.station_opening_hours_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: station_owner_profiles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.station_owner_profiles (
    id bigint NOT NULL,
    bank_account character varying(255),
    bank_name character varying(255),
    business_name character varying(255),
    contact_email character varying(255) NOT NULL,
    contact_phone character varying(255) NOT NULL,
    full_name character varying(255),
    identity_number character varying(255),
    owner_type character varying(255) NOT NULL,
    pdf_file_path character varying(255) NOT NULL,
    pdf_public_id character varying(255) NOT NULL,
    registration_code character varying(255) NOT NULL,
    rejection_reason text,
    reviewed_at timestamp(6) without time zone,
    status character varying(255) NOT NULL,
    submitted_at timestamp(6) without time zone,
    tax_code character varying(255),
    user_id bigint,
    CONSTRAINT station_owner_profiles_owner_type_check CHECK (((owner_type)::text = ANY ((ARRAY['ENTERPRISE'::character varying, 'INDIVIDUAL'::character varying])::text[]))),
    CONSTRAINT station_owner_profiles_status_check CHECK (((status)::text = ANY ((ARRAY['SUBMITTED'::character varying, 'UNDER_REVIEW'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying])::text[])))
);


--
-- Name: station_owner_profiles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.station_owner_profiles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.station_owner_profiles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: station_photos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.station_photos (
    id bigint NOT NULL,
    caption character varying(255),
    cloudinary_public_id character varying(255),
    created_at timestamp(6) without time zone,
    display_order integer NOT NULL,
    image_url character varying(500) NOT NULL,
    station_id bigint NOT NULL
);


--
-- Name: station_photos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.station_photos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.station_photos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.stations (
    id bigint NOT NULL,
    address character varying(255) NOT NULL,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    description character varying(2000),
    is_flagged_low_quality boolean NOT NULL,
    latitude double precision,
    longitude double precision,
    name character varying(255) NOT NULL,
    owner_id bigint NOT NULL,
    rate real,
    status character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    CONSTRAINT stations_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'ACTIVE'::character varying, 'INACTIVE'::character varying, 'SUSPENDED'::character varying])::text[])))
);


--
-- Name: stations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.stations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: transactions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.transactions (
    id bigint NOT NULL,
    amount numeric(12,2) NOT NULL,
    app_trans_id character varying(255),
    created_at timestamp(6) without time zone,
    gateway_transaction_id character varying(255),
    order_url text,
    payment_method character varying(255),
    return_code integer,
    status character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    zp_trans_token character varying(255),
    invoice_id bigint NOT NULL,
    CONSTRAINT transactions_payment_method_check CHECK (((payment_method)::text = ANY ((ARRAY['MOMO'::character varying, 'ZALOPAY'::character varying, 'BANK_TRANSFER'::character varying])::text[]))),
    CONSTRAINT transactions_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'SUCCESS'::character varying, 'FAILED'::character varying])::text[])))
);


--
-- Name: transactions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_roles (
    user_id bigint NOT NULL,
    role_id bigint NOT NULL
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    auth_provider character varying(255) NOT NULL,
    avatar_public_id character varying(255),
    avatar_url character varying(255),
    birthday date,
    created_at timestamp(6) without time zone,
    email character varying(255),
    email_verified boolean NOT NULL,
    full_name character varying(255) NOT NULL,
    gender character varying(255),
    password character varying(255) NOT NULL,
    password_changed_at timestamp(6) with time zone,
    phone_number character varying(255),
    phone_verified boolean NOT NULL,
    provider_id character varying(255),
    status character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    CONSTRAINT users_auth_provider_check CHECK (((auth_provider)::text = ANY ((ARRAY['LOCAL'::character varying, 'GOOGLE'::character varying])::text[]))),
    CONSTRAINT users_gender_check CHECK (((gender)::text = ANY ((ARRAY['MALE'::character varying, 'FEMALE'::character varying, 'OTHER'::character varying])::text[]))),
    CONSTRAINT users_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying, 'BLOCKED'::character varying, 'DELETED'::character varying])::text[])))
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: vehicle_connector_types; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.vehicle_connector_types (
    vehicle_id bigint NOT NULL,
    connector_type character varying(255),
    CONSTRAINT vehicle_connector_types_connector_type_check CHECK (((connector_type)::text = ANY ((ARRAY['SOCKET_220V'::character varying, 'VINFAST_STD'::character varying, 'DATBIKE_FAST'::character varying, 'IEC_TYPE_2'::character varying, 'OTHER'::character varying])::text[])))
);


--
-- Name: vehicles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.vehicles (
    id bigint NOT NULL,
    brand character varying(255) NOT NULL,
    in_use boolean NOT NULL,
    model_name character varying(255) NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: vehicles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.vehicles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vehicles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bookings bookings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookings
    ADD CONSTRAINT bookings_pkey PRIMARY KEY (id);


--
-- Name: chargers chargers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chargers
    ADD CONSTRAINT chargers_pkey PRIMARY KEY (id);


--
-- Name: charging_sessions charging_sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.charging_sessions
    ADD CONSTRAINT charging_sessions_pkey PRIMARY KEY (id);


--
-- Name: complaint_responses complaint_responses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.complaint_responses
    ADD CONSTRAINT complaint_responses_pkey PRIMARY KEY (id);


--
-- Name: complaints complaints_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.complaints
    ADD CONSTRAINT complaints_pkey PRIMARY KEY (id);


--
-- Name: event_publication event_publication_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.event_publication
    ADD CONSTRAINT event_publication_pkey PRIMARY KEY (id);


--
-- Name: invoices invoices_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invoices
    ADD CONSTRAINT invoices_pkey PRIMARY KEY (id);


--
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);


--
-- Name: ports ports_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ports
    ADD CONSTRAINT ports_pkey PRIMARY KEY (id);


--
-- Name: price_settings price_settings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.price_settings
    ADD CONSTRAINT price_settings_pkey PRIMARY KEY (id);


--
-- Name: reviews reviews_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT reviews_pkey PRIMARY KEY (id);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- Name: station_opening_hours station_opening_hours_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.station_opening_hours
    ADD CONSTRAINT station_opening_hours_pkey PRIMARY KEY (id);


--
-- Name: station_owner_profiles station_owner_profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.station_owner_profiles
    ADD CONSTRAINT station_owner_profiles_pkey PRIMARY KEY (id);


--
-- Name: station_photos station_photos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.station_photos
    ADD CONSTRAINT station_photos_pkey PRIMARY KEY (id);


--
-- Name: stations stations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stations
    ADD CONSTRAINT stations_pkey PRIMARY KEY (id);


--
-- Name: transactions transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_pkey PRIMARY KEY (id);


--
-- Name: station_owner_profiles uk14gptybytem9eu9d4x1l3x5yf; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.station_owner_profiles
    ADD CONSTRAINT uk14gptybytem9eu9d4x1l3x5yf UNIQUE (registration_code);


--
-- Name: station_owner_profiles uk3buj48rrkn422o3wmlfyejgad; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.station_owner_profiles
    ADD CONSTRAINT uk3buj48rrkn422o3wmlfyejgad UNIQUE (pdf_public_id);


--
-- Name: station_owner_profiles uk5cal3yb93uf93x986xsul9ni5; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.station_owner_profiles
    ADD CONSTRAINT uk5cal3yb93uf93x986xsul9ni5 UNIQUE (user_id);


--
-- Name: transactions uk65wgqoi0pax5r43juh7ikbqd9; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT uk65wgqoi0pax5r43juh7ikbqd9 UNIQUE (app_trans_id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: users uk9q63snka3mdh91as4io72espi; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk9q63snka3mdh91as4io72espi UNIQUE (phone_number);


--
-- Name: roles ukofx66keruapi6vyqpv6f2or37; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT ukofx66keruapi6vyqpv6f2or37 UNIQUE (name);


--
-- Name: invoices ukpa4f04a5qcpc80w6x1ry6v6o1; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invoices
    ADD CONSTRAINT ukpa4f04a5qcpc80w6x1ry6v6o1 UNIQUE (number);


--
-- Name: user_roles user_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT user_roles_pkey PRIMARY KEY (user_id, role_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: vehicles vehicles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vehicles
    ADD CONSTRAINT vehicles_pkey PRIMARY KEY (id);


--
-- Name: station_images fkf6pvir20nndl301wmt3c64qr0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.station_images
    ADD CONSTRAINT fkf6pvir20nndl301wmt3c64qr0 FOREIGN KEY (station_id) REFERENCES public.stations(id);


--
-- Name: user_roles fkh8ciramu9cc9q3qcqiv4ue8a6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fkh8ciramu9cc9q3qcqiv4ue8a6 FOREIGN KEY (role_id) REFERENCES public.roles(id);


--
-- Name: user_roles fkhfh9dx7w3ubf1co1vdev94g3f; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fkhfh9dx7w3ubf1co1vdev94g3f FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: transactions fkm5goxujeqrwf774cgr0r04553; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT fkm5goxujeqrwf774cgr0r04553 FOREIGN KEY (invoice_id) REFERENCES public.invoices(id);


--
-- Name: station_owner_profiles fkm5kyjd3s7vjl54u0dy1f7xoig; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.station_owner_profiles
    ADD CONSTRAINT fkm5kyjd3s7vjl54u0dy1f7xoig FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: ports fknpnmmlaih9opp95cyno0rg2jo; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ports
    ADD CONSTRAINT fknpnmmlaih9opp95cyno0rg2jo FOREIGN KEY (charger_id) REFERENCES public.chargers(id);


--
-- Name: vehicle_connector_types fkps8qucijwxijydrmb2t4jbye4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vehicle_connector_types
    ADD CONSTRAINT fkps8qucijwxijydrmb2t4jbye4 FOREIGN KEY (vehicle_id) REFERENCES public.vehicles(id);


--
-- Name: station_opening_hours fkqg7lpuc48mccg49cpr163v7j4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.station_opening_hours
    ADD CONSTRAINT fkqg7lpuc48mccg49cpr163v7j4 FOREIGN KEY (station_id) REFERENCES public.stations(id);


--
-- PostgreSQL database dump complete
--


