package com.project.evgo.payment.internal;

import com.project.evgo.sharedkernel.enums.PaymentMethod;
import com.project.evgo.sharedkernel.enums.TransactionStatus;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * Transaction entity - represents a payment transaction.
 * Internal - not accessible by other modules.
 */
@Entity
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "transactions")
public class Transaction {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "invoice_id", nullable = false)
    private Invoice invoice;

    @Enumerated(EnumType.STRING)
    @Column(name = "payment_method")
    private PaymentMethod paymentMethod;

    /**
     * Maps to ZaloPay's zp_trans_id (the gateway's own transaction ID).
     * Populated on successful payment callback.
     */
    @Column(name = "gateway_transaction_id")
    private String gatewayTransactionId;

    /**
     * ZaloPay unique transaction identifier (format: yyMMdd_UUID8).
     * Generated by us; used in all ZaloPay API calls. Replaces generic
     * gatewayRequestId.
     */
    @Column(name = "app_trans_id", unique = true)
    private String appTransId;

    @Column(nullable = false, precision = 12, scale = 2)
    private BigDecimal amount;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private TransactionStatus status = TransactionStatus.PENDING;

    /**
     * ZaloPay return_code: 1 = success, others = failure.
     * Stored as Integer for numeric comparison in callback handling.
     */
    @Column(name = "return_code")
    private Integer returnCode;

    /**
     * ZaloPay App-to-App token returned by createOrder.
     * Mobile client uses this value to open the ZaloPay Sandbox app directly.
     */
    @Column(name = "zp_trans_token")
    private String zpTransToken;

    /**
     * Deep-link URL returned by ZaloPay createOrder.
     * Mobile calls Linking.openURL(orderUrl) to launch ZaloPay app.
     */
    @Column(name = "order_url", columnDefinition = "TEXT")
    private String orderUrl;

    @CreationTimestamp
    private LocalDateTime createdAt;

    @UpdateTimestamp
    private LocalDateTime updatedAt;
}
